CREATE TABLE profile_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id UUID NOT NULL REFERENCES children(id) ON DELETE RESTRICT,
    from_status VARCHAR(20),
    from_stage VARCHAR(30),
    to_status VARCHAR(20) NOT NULL,
    to_stage VARCHAR(30),
    reason VARCHAR(30) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL,
    from_criteria JSONB NOT NULL,
    to_criteria JSONB NOT NULL,
    CONSTRAINT ck_profile_history_status
        CHECK ((from_status IS NULL OR from_status IN ('APPLIED', 'UNSUPPORTED'))
            AND to_status IN ('APPLIED', 'UNSUPPORTED')),
    CONSTRAINT ck_profile_history_stage
        CHECK ((from_stage IS NULL OR from_stage IN ('INFANT', 'TODDLER', 'ACTIVE_CHILD'))
            AND (to_stage IS NULL OR to_stage IN ('INFANT', 'TODDLER', 'ACTIVE_CHILD'))),
    CONSTRAINT ck_profile_history_from_consistency
        CHECK ((from_status IS NULL AND from_stage IS NULL)
            OR (from_status IS NOT NULL AND ((from_status = 'APPLIED' AND from_stage IS NOT NULL)
                OR (from_status = 'UNSUPPORTED' AND from_stage IS NULL)))),
    CONSTRAINT ck_profile_history_to_consistency
        CHECK ((to_status = 'APPLIED' AND to_stage IS NOT NULL)
            OR (to_status = 'UNSUPPORTED' AND to_stage IS NULL)),
    CONSTRAINT ck_profile_history_reason
        CHECK ((reason = 'REGISTERED' AND from_status IS NULL)
            OR (reason IN ('AGE_CHANGED', 'BIRTH_DATE_UPDATED') AND from_status IS NOT NULL
                AND (from_status IS DISTINCT FROM to_status OR from_stage IS DISTINCT FROM to_stage))),
    CONSTRAINT ck_profile_history_criteria_array
        CHECK (jsonb_typeof(from_criteria) = 'array' AND jsonb_typeof(to_criteria) = 'array')
);

CREATE INDEX ix_profile_history_child_month ON profile_history (child_id, changed_at, id);
CREATE UNIQUE INDEX uq_profile_history_registration ON profile_history (child_id) WHERE reason = 'REGISTERED';
